baseURL = 'https://www.cyansun.art/'
languageCode = 'zh-cn'
title = 'CyanSun'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    ShowReadingTime = true
    ShowShareButtons = true

    # ğŸ  é¦–é¡µåç‰‡è®¾ç½®
    [params.profileMode]
        enabled = true
        title = "Hi, I'm CyanSun ğŸ‘‹"
        subtitle = "ğŸ“® the.cyansun@gmail.com \n\n è™šæ‹Ÿäº§å“å¼€å‘è€… | AI æ¢ç´¢è€… | å‡ºæµ·App"
        imageUrl = "https://github.com/qingyang3018.png"
        imageTitle = "Avatar"
        imageWidth = 150
        imageHeight = 150

        [[params.profileMode.buttons]]
            name = "ğŸ“„ é˜…è¯»æ–‡ç«  (Enter Blog)"
            url = "posts"

        [[params.profileMode.buttons]]
            name = "ğŸ—‚ï¸ å½’æ¡£ (Archives)"
            url = "archives"

    # ğŸ”— ç¤¾äº¤å›¾æ ‡
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/qingyang3018"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:the.cyansun@gmail.com"